export { PRODUCT_NAME, RIOT_LEGAL_NOTICE } from './constants';

export {
  HealthResponseSchema,
  ProviderModeSchema,
  createHealthResponse,
  type HealthResponse,
  type ProviderMode,
} from './health';

export { ProviderIdSchema, PROVIDER_IDS, type ProviderId } from './provider-id';

export {
  DomainError,
  DomainErrorCodeSchema,
  InvalidRiotIdError,
  UnsupportedPlatformRouteError,
  InvalidRegionalRouteError,
  ValidationFailureError,
  ProviderNotConfiguredError,
  ProviderUnauthorizedError,
  ProviderForbiddenError,
  ProviderResponseInvalidError,
  ResourceNotFoundError,
  ProviderRateLimitedError,
  ProviderUnavailableError,
  AccountIdentityConflictError,
  RefreshInProgressError,
  RefreshCooldownError,
  QueueUnavailableError,
  DatabaseUnavailableError,
  InvalidCursorError,
  ChampionNotFoundError,
  ChampionStatsPositionRequiredError,
  ChampionStatsInvalidFilterError,
  serializeDomainError,
  ApiErrorResponseSchema,
  type DomainErrorCode,
  type ApiErrorResponse,
} from './errors';

export {
  RiotIdSchema,
  parseRiotId,
  formatRiotId,
  RIOT_GAME_NAME_MAX_LENGTH,
  RIOT_TAG_LINE_MAX_LENGTH,
  type RiotId,
} from './riot-id';

export {
  PLATFORM_ROUTES,
  REGIONAL_ROUTES,
  EXCLUDED_PLATFORM_ALIASES,
  PlatformRouteSchema,
  RegionalRouteSchema,
  parsePlatformRoute,
  parseRegionalRoute,
  getRegionalRouteForPlatform,
  getPlatformDisplayName,
  listSupportedPlatforms,
  getPlatformToRegionalMap,
  getRoutingKindForEndpointCategory,
  requiresPlatformRouting,
  requiresRegionalRouting,
  getPlatformApiHost,
  getRegionalApiHost,
  getApiHostForEndpointCategory,
  type PlatformRoute,
  type RegionalRoute,
  type RiotEndpointCategory,
} from './routing';

export { RankTierSchema, RankDivisionSchema, type RankTier, type RankDivision } from './ranks';

export {
  RANK_SEGMENT_IDS,
  RANK_SEGMENTS,
  APEX_RANK_TIERS,
  HIGH_RANK_TIERS,
  MID_RANK_TIERS,
  LOW_RANK_TIERS,
  rankSegmentForTier,
  parseRankSegmentId,
  hasCompleteApexRepresentation,
  assertTierInSegment,
  type RankSegmentId,
  type RankSegmentTiers,
} from './rank-segments';

export {
  RankScopeSchema,
  parseRankScope,
  rankScopeEquals,
  serializeRankScopeCacheToken,
  parseRankScopeCacheToken,
  exactTiersForRankScope,
  resolveRankScopeReadStrategy,
  legacyTierFilterToRankScope,
  assertProductRankScope,
  resolutionStatusAllowsExactOrSegmentProductScope,
  type RankScope,
  type RankScopeReadStrategy,
  type LegacyChampionStatsTierFilter,
} from './rank-scope';

export {
  emptyMergeableChampionAggregateTotals,
  mergeChampionAggregateTotals,
  deriveSegmentWinRate,
  type MergeableChampionAggregateTotals,
} from './rank-aware-merge';

export {
  CHAMPION_STATS_RANKING_FLOOR,
  RankAwareProductQualityMetaSchema,
  buildRankAwareProductQualityMeta,
  type RankAwareProductQualityMeta,
} from './rank-aware-eligibility';

export { QueueTypeSchema, type QueueType } from './queues';

export {
  ParticipantRankResolutionStatusSchema,
  AGGREGATE_UNKNOWN_RANK_TIER,
  PARTICIPANT_RANK_OBSERVATION_FRESHNESS_MS,
  classifyParticipantRankForAggregates,
  initialParticipantRankResolutionStatus,
  isRankedSoloOrFlexQueue,
  type ParticipantRankResolutionStatus,
  type ParticipantRankAggregateClassification,
  type ClassifyParticipantRankInput,
} from './participant-rank-resolution';

export {
  emptyRankResolutionStateCounts,
  rankCoverageDenominator,
  computeRankQualityMetrics,
  classifyExactRankCoverageHealth,
  bumpRankResolutionStateCount,
  RANK_COVERAGE_UNHEALTHY_WARNING,
  type RankResolutionStateCounts,
  type RankQualityMetrics,
  type ExactRankCoverageHealth,
  type ExactRankCoverageHealthResult,
} from './participant-rank-quality';

export {
  RANKED_SOLO_QUEUE_ID,
  RANKED_FLEX_QUEUE_ID,
  NORMAL_DRAFT_QUEUE_ID,
  NORMAL_BLIND_QUEUE_ID,
  QUICKPLAY_QUEUE_ID,
  ARAM_QUEUE_ID,
  ARENA_QUEUE_ID,
  SWIFTPLAY_QUEUE_ID,
  CUSTOM_QUEUE_ID,
  MATCH_QUEUE_LABELS,
  PlayerMatchQueueCategorySchema,
  getMatchQueueLabel,
  resolveMatchQueueCategoryFilter,
  supportsStandardPositions,
  type PlayerMatchQueueCategory,
} from './match-queues';

export { TeamPositionSchema, type TeamPosition } from './positions';

export {
  NormalizedPositionSchema,
  normalizeParticipantPosition,
  getNormalizedPositionLabel,
  legacyBuggyPublicRole,
  type NormalizedPosition,
  type NormalizeParticipantPositionInput,
} from './normalized-position';

export { PatchVersionSchema, parsePatchVersion, type PatchVersion } from './patch';

export {
  PlayerAccountSchema,
  RankedEntrySchema,
  type PlayerAccount,
  type RankedEntry,
} from './player';

export {
  MatchParticipantSchema,
  MatchSummarySchema,
  type MatchParticipant,
  type MatchSummary,
} from './match';

export { ChampionMasterySchema, type ChampionMastery } from './mastery';

export {
  ApiSuccessResponseSchema,
  createApiSuccessResponse,
  PaginatedResponseSchema,
  PaginationQuerySchema,
  createPaginatedResponse,
  type ApiSuccessResponse,
  type PaginatedResponse,
  type PaginationQuery,
} from './api';

export type { GameDataProvider } from './provider';

export {
  MATCH_INGESTION_QUEUE_NAME,
  MATCH_INGESTION_JOB_NAME,
  MATCH_INGESTION_NORMALIZATION_VERSION,
  MatchIngestionJobPayloadSchema,
  MatchIngestionJobTypeSchema,
  buildMatchIngestionIdempotencyKey,
  buildMatchIngestionBullMqJobId,
  CHAMPION_AGGREGATION_QUEUE_NAME,
  CHAMPION_AGGREGATION_JOB_NAME,
  ChampionAggregationJobPayloadSchema,
  ChampionAggregationJobTypeSchema,
  buildChampionAggregationBullMqJobId,
  PARTICIPANT_RANK_ENRICHMENT_QUEUE_NAME,
  PARTICIPANT_RANK_ENRICHMENT_JOB_NAME,
  ParticipantRankEnrichmentJobPayloadSchema,
  ParticipantRankEnrichmentJobTypeSchema,
  buildParticipantRankEnrichmentBullMqJobId,
  CHAMPION_AI_INSIGHT_QUEUE_NAME,
  CHAMPION_AI_INSIGHT_JOB_NAME,
  PLAYER_AI_PLAYSTYLE_QUEUE_NAME,
  PLAYER_AI_PLAYSTYLE_JOB_NAME,
  ChampionAiInsightJobPayloadSchema,
  ChampionAiInsightJobTypeSchema,
  buildChampionAiInsightBullMqJobId,
  PlayerPlaystyleInsightJobPayloadSchema,
  PlayerPlaystyleInsightJobTypeSchema,
  buildPlayerPlaystyleInsightBullMqJobId,
  BULLMQ_DEFAULT_PREFIX,
  parseBullMqRedisConnectionInfo,
  createBullMqConnectionOptions,
  resolveBullMqPrefix,
  type MatchIngestionQueueName,
  type MatchIngestionJobName,
  type MatchIngestionJobPayload,
  type MatchIngestionJobType,
  type ChampionAggregationQueueName,
  type ChampionAggregationJobName,
  type ChampionAggregationJobPayload,
  type ChampionAggregationJobType,
  type ParticipantRankEnrichmentQueueName,
  type ParticipantRankEnrichmentJobName,
  type ParticipantRankEnrichmentJobPayload,
  type ParticipantRankEnrichmentJobType,
  type ChampionAiInsightQueueName,
  type ChampionAiInsightJobName,
  type ChampionAiInsightJobPayload,
  type ChampionAiInsightJobType,
  type PlayerAiPlaystyleQueueName,
  type PlayerAiPlaystyleJobName,
  type PlayerPlaystyleInsightJobPayload,
  type PlayerPlaystyleInsightJobType,
  type BullMqRedisConnectionInfo,
} from './job-queues';

export {
  serializeChampionStatsGenerationScope,
  buildChampionStatsGenerationKey,
  buildChampionStatsTableCacheKey,
  buildChampionStatsChampionCacheKey,
  buildChampionStatsFiltersCacheKey,
  buildChampionBuildGenerationKey,
  buildChampionBuildCacheKey,
  buildChampionMatchupGenerationKey,
  buildChampionMatchupCacheKey,
  type ChampionStatsGenerationScope,
  type ChampionStatsTableCacheKeyInput,
  type ChampionStatsChampionCacheKeyInput,
  type ChampionStatsFiltersCacheKeyInput,
  type ChampionBuildCacheKeyInput,
  type ChampionMatchupCacheKeyInput,
} from './champion-stats-cache';

export {
  CHAMPION_STATS_DISCLAIMER,
  RANK_TIER_SEMANTICS,
  CHAMPION_STATS_FILTER_QUEUE_IDS,
  ChampionRankingPositionSchema,
  SampleConfidenceSchema,
  ConfidenceIntervalSchema,
  ChampionStatsFreshnessSchema,
  ChampionStatsEmptyReasonSchema,
  SampleScopeSchema,
  ChampionStatsTierFilterSchema,
  AggregateDimensionsSchema,
  ChampionSummarySchema,
  ChampionAbilitySlotSchema,
  ChampionAbilitySummarySchema,
  ChampionDetailSchema,
  ChampionAggregateMetricsSchema,
  ChampionAggregateRowSchema,
  ChampionStatsSortBySchema,
  ChampionStatsSortDirectionSchema,
  ChampionStatsTableQuerySchema,
  ChampionStatsQuerySchema,
  ChampionStatsResolvedFiltersSchema,
  ChampionStatsRequestedFiltersSchema,
  ChampionStatsEnvelopeMetaSchema,
  ChampionStatsPaginationSchema,
  ChampionStatsTableResponseSchema,
  ChampionPositionBreakdownEntrySchema,
  ChampionExactStatsSchema,
  ChampionStatsResponseSchema,
  ChampionListResponseSchema,
  ChampionDetailResponseSchema,
  ChampionStatsFilterQueueSchema,
  ChampionStatsFiltersResponseSchema,
  buildChampionStatsFilterQueue,
  type ChampionRankingPosition,
  type SampleConfidence,
  type ConfidenceInterval,
  type ChampionStatsFreshness,
  type ChampionStatsEmptyReason,
  type SampleScope,
  type ChampionStatsTierFilter,
  type AggregateDimensions,
  type ChampionSummary,
  type ChampionAbilitySlot,
  type ChampionAbilitySummary,
  type ChampionDetail,
  type ChampionAggregateMetrics,
  type ChampionAggregateRow,
  type ChampionStatsSortBy,
  type ChampionStatsSortDirection,
  type ChampionStatsTableQuery,
  type ChampionStatsQuery,
  type ChampionStatsResolvedFilters,
  type ChampionStatsRequestedFilters,
  type ChampionStatsPagination,
  type ChampionStatsTableResponse,
  type ChampionPositionBreakdownEntry,
  type ChampionExactStats,
  type ChampionStatsResponse,
  type ChampionListResponse,
  type ChampionDetailResponse,
  type ChampionStatsFilterQueue,
  type ChampionStatsFiltersResponse,
} from './champion-api';

export {
  ChampionBuildSampleBandSchema,
  ChampionBuildStaticIdentitySchema,
  ChampionBuildRowMetricsSchema,
  ChampionStartingItemSetSchema,
  ChampionCoreBuildSchema,
  ChampionBootRowSchema,
  ChampionRuneSetupSchema,
  ChampionSpellPairSchema,
  ChampionSkillKeySchema,
  ChampionSkillOrderRowSchema,
  ChampionBuildsEmptyReasonSchema,
  ChampionBuildsQuerySchema,
  ChampionBuildsResponseSchema,
  type ChampionBuildSampleBand,
  type ChampionBuildStaticIdentity,
  type ChampionBuildRowMetrics,
  type ChampionStartingItemSet,
  type ChampionCoreBuild,
  type ChampionBootRow,
  type ChampionRuneSetup,
  type ChampionSpellPair,
  type ChampionSkillKey,
  type ChampionSkillOrderRow,
  type ChampionBuildsEmptyReason,
  type ChampionBuildsQuery,
  type ChampionBuildsResponse,
} from './champion-builds';

export {
  ChampionMatchupOpponentSchema,
  ChampionMatchupRowSchema,
  ChampionMatchupsEmptyReasonSchema,
  ChampionMatchupsQuerySchema,
  ChampionMatchupsResponseSchema,
  type ChampionMatchupOpponent,
  type ChampionMatchupRow,
  type ChampionMatchupsEmptyReason,
  type ChampionMatchupsQuery,
  type ChampionMatchupsResponse,
} from './champion-matchups';

export { DEFAULT_AI_MODEL } from './ai-runtime';

export {
  CHAMPION_AI_DISCLAIMER,
  CHAMPION_AI_PROMPT_VERSION,
  ChampionAiInsightStatusSchema,
  ChampionAiInsightsEmptyReasonSchema,
  ChampionAiInsightsQuerySchema,
  ChampionAiPublicInsightSchema,
  ChampionAiInsightsResponseSchema,
  ChampionAiGroundedClaimSchema,
  ChampionAiStoredInsightSchema,
  type ChampionAiInsightStatus,
  type ChampionAiInsightsEmptyReason,
  type ChampionAiInsightsQuery,
  type ChampionAiPublicInsight,
  type ChampionAiInsightsResponse,
  type ChampionAiGroundedClaim,
  type ChampionAiStoredInsight,
} from './champion-insights';

export {
  PLAYER_PLAYSTYLE_AI_DISCLAIMER,
  PLAYER_PLAYSTYLE_PROMPT_VERSION,
  PlayerPlaystyleMetricIdSchema,
  PlayerPlaystyleDirectionSchema,
  PlayerPlaystyleSampleBandSchema,
  PlayerAiInsightStatusSchema,
  PlayerPlaystyleEmptyReasonSchema,
  PlayerPlaystyleBaselineSchema,
  PlayerMetricComparisonSchema,
  PlayerPlaystylePublicInsightSchema,
  PlayerPlaystyleResponseSchema,
  PlayerPlaystyleGroundedClaimSchema,
  PlayerPlaystyleStoredInsightSchema,
  type PlayerPlaystyleMetricId,
  type PlayerPlaystyleDirection,
  type PlayerPlaystyleSampleBand,
  type PlayerAiInsightStatus,
  type PlayerPlaystyleEmptyReason,
  type PlayerPlaystyleBaseline,
  type PlayerMetricComparison,
  type PlayerPlaystylePublicInsight,
  type PlayerPlaystyleResponse,
  type PlayerPlaystyleGroundedClaim,
  type PlayerPlaystyleStoredInsight,
} from './player-playstyle';

export {
  ABILITY_SLOTS,
  extractChampionAbilities,
  normalizeAbilityDescription,
  snapshotDataDragonAbilities,
  type AbilityIconUrlBuilders,
  type StoredChampionAbilities,
  type StoredChampionPassive,
  type StoredChampionSpell,
} from './champion-abilities';

export {
  PublicMatchTeamSideSchema,
  PublicMatchTimelineStatusSchema,
  PublicMatchProductCoverageSchema,
  PublicMatchItemSlotSchema,
  PublicMatchObjectiveSchema,
  PublicMatchParticipantSchema,
  PublicMatchTeamTotalsSchema,
  PublicMatchTeamSchema,
  PublicMatchTimelineSchema,
  PublicMatchDetailSchema,
  MATCH_OBJECTIVE_DISPLAY_ORDER,
  matchTeamSide,
  parseMatchTeamObjectives,
  sortMatchParticipants,
  sortMatchTeams,
  winningSideFromTeams,
  participantHasTimelineMetrics,
  type PublicMatchTeamSide,
  type PublicMatchTimelineStatus,
  type PublicMatchProductCoverage,
  type PublicMatchItemSlot,
  type PublicMatchObjective,
  type PublicMatchParticipant,
  type PublicMatchTeamTotals,
  type PublicMatchTeam,
  type PublicMatchTimeline,
  type PublicMatchDetail,
} from './match-detail';

export {
  PublicMatchTimelineCoverageSchema,
  PERSISTED_TIMELINE_EVENT_TYPES,
  PublicMatchTimelineEventTypeSchema,
  PublicMatchTimelineParticipantSchema,
  PublicMatchPositionSchema,
  PublicMatchTimelineEventSchema,
  PublicMatchKillEventSchema,
  PublicMatchObjectiveEventTypeSchema,
  PublicMatchObjectiveEventSchema,
  PublicMatchTimelineFrameSchema,
  PublicMatchGoldSeriesSchema,
  PublicMatchTimelineDetailSchema,
  mapPublicObjectiveType,
  publicSkillSlotLabel,
  deriveTeamGoldSeries,
  coverageFromEventAndFrameRows,
  type PublicMatchTimelineCoverage,
  type PublicMatchTimelineEventType,
  type PublicMatchTimelineParticipant,
  type PublicMatchPosition,
  type PublicMatchTimelineEvent,
  type PublicMatchKillEvent,
  type PublicMatchObjectiveEventType,
  type PublicMatchObjectiveEvent,
  type PublicMatchTimelineFrame,
  type PublicMatchGoldSeries,
  type PublicMatchTimelineDetail,
} from './match-timeline';

export {
  PlayerRefreshStateSchema,
  PlayerSafeWarningSchema,
  PublicPlayerSchema,
  PublicRankSummarySchema,
  PublicMasterySummarySchema,
  PublicMatchIngestionStatusSchema,
  PublicMatchSummarySchema,
  PlayerRefreshStatusSchema,
  PlayerSearchResponseSchema,
  PlayerProfileResponseSchema,
  PlayerSearchRequestSchema,
  PlayerRefreshRequestSchema,
  PlayerRanksQuerySchema,
  PlayerMasteryQuerySchema,
  PlayerMatchesQuerySchema,
  CursorPageSchema,
  type PlayerRefreshState,
  type PlayerSafeWarning,
  type PublicPlayer,
  type PublicRankSummary,
  type PublicMasterySummary,
  type PublicMatchIngestionStatus,
  type PublicMatchSummary,
  type PlayerRefreshStatus,
  type PlayerSearchResponse,
  type PlayerProfileResponse,
  type PlayerSearchRequest,
  type PlayerRefreshRequest,
  type PlayerRanksQuery,
  type PlayerMasteryQuery,
  type PlayerMatchesQuery,
} from './player-api';
