export const MATCH_INGESTION_QUEUE = Symbol('MATCH_INGESTION_QUEUE');
export const MATCH_TIMELINE_QUEUE = Symbol('MATCH_TIMELINE_QUEUE');
export const CHAMPION_AI_INSIGHT_QUEUE = Symbol('CHAMPION_AI_INSIGHT_QUEUE');
export const PLAYER_AI_PLAYSTYLE_QUEUE = Symbol('PLAYER_AI_PLAYSTYLE_QUEUE');
export const REDIS_CONNECTION = Symbol('REDIS_CONNECTION');
