export const MATCH_INGESTION_QUEUE = Symbol('MATCH_INGESTION_QUEUE');
export const CHAMPION_AI_INSIGHT_QUEUE = Symbol('CHAMPION_AI_INSIGHT_QUEUE');
export const REDIS_CONNECTION = Symbol('REDIS_CONNECTION');
