/** Minimal Data Dragon fixtures for unit tests (no live CDN). */

export const MOCK_DDRAGON_VERSION = '14.15.1';

export const MOCK_DDRAGON_VERSIONS = [MOCK_DDRAGON_VERSION, '14.14.1', '14.13.1'];

export const MOCK_DDRAGON_CHAMPION_JSON = {
  type: 'champion',
  format: 'standAloneComplex',
  version: MOCK_DDRAGON_VERSION,
  data: {
    Tryndamere: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Tryndamere',
      key: '23',
      name: 'Tryndamere',
      title: 'the Barbarian King',
      blurb: 'Fueled by unbridled fury and rage...',
      info: { attack: 10, defense: 5, magic: 2, difficulty: 5 },
      image: {
        full: 'Tryndamere.png',
        sprite: 'champion4.png',
        group: 'champion',
        x: 288,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Fighter', 'Assassin'],
      partype: 'Fury',
      stats: {},
    },
    Yasuo: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Yasuo',
      key: '157',
      name: 'Yasuo',
      title: 'the Unforgiven',
      blurb: 'An Ionian of deep resolve...',
      info: { attack: 8, defense: 4, magic: 4, difficulty: 10 },
      image: {
        full: 'Yasuo.png',
        sprite: 'champion4.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Fighter', 'Assassin'],
      partype: 'Flow',
      stats: {},
    },
    Orianna: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Orianna',
      key: '61',
      name: 'Orianna',
      title: 'the Lady of Clockwork',
      blurb: '',
      info: { attack: 4, defense: 3, magic: 9, difficulty: 7 },
      image: {
        full: 'Orianna.png',
        sprite: 'champion2.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Mage', 'Support'],
      partype: 'Mana',
      stats: {},
    },
    DrMundo: {
      version: MOCK_DDRAGON_VERSION,
      id: 'DrMundo',
      key: '36',
      name: 'Dr. Mundo',
      title: 'the Madman of Zaun',
      blurb: '',
      info: { attack: 5, defense: 7, magic: 6, difficulty: 5 },
      image: {
        full: 'DrMundo.png',
        sprite: 'champion0.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Fighter', 'Tank'],
      partype: 'None',
      stats: {},
    },
    Yone: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Yone',
      key: '777',
      name: 'Yone',
      title: 'the Unforgotten',
      blurb: '',
      info: { attack: 8, defense: 4, magic: 4, difficulty: 8 },
      image: {
        full: 'Yone.png',
        sprite: 'champion5.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Assassin', 'Fighter'],
      partype: 'Flow',
      stats: {},
    },
    Graves: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Graves',
      key: '104',
      name: 'Graves',
      title: 'the Outlaw',
      blurb: '',
      info: { attack: 8, defense: 5, magic: 3, difficulty: 3 },
      image: {
        full: 'Graves.png',
        sprite: 'champion1.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Marksman'],
      partype: 'Mana',
      stats: {},
    },
    Shyvana: {
      version: MOCK_DDRAGON_VERSION,
      id: 'Shyvana',
      key: '102',
      name: 'Shyvana',
      title: 'the Half-Dragon',
      blurb: '',
      info: { attack: 8, defense: 6, magic: 3, difficulty: 4 },
      image: {
        full: 'Shyvana.png',
        sprite: 'champion3.png',
        group: 'champion',
        x: 0,
        y: 0,
        w: 48,
        h: 48,
      },
      tags: ['Fighter', 'Tank'],
      partype: 'Fury',
      stats: {},
    },
  },
};

export function expectedTryndamereIconUrl(baseUrl = 'https://ddragon.leagueoflegends.com'): string {
  return `${baseUrl}/cdn/${MOCK_DDRAGON_VERSION}/img/champion/Tryndamere.png`;
}
